import { Timestamp } from "firebase/firestore";

export interface ClientLink {
  id: string;
  label: string;
  linkText: string;
  url: string;
}

export interface ClientForm {
  id: string;
  label: string;
  url: string;
}

export type ApRecurrence = "weekly" | "biweekly" | "monthly";

export interface ApCalendar {
  startDate: string; // ISO date, e.g. "2026-01-05"
  recurrence: ApRecurrence;
  // Dates generated from startDate+recurrence but excluded (e.g. holidays), ISO date strings
  skipDates: string[];
  // One-off dates added outside the recurrence pattern, ISO date strings
  extraDates: string[];
  // Rolling-window generated dates, ISO date strings — regenerated by the top-up job,
  // never rewritten once a date has been assigned to a transaction row
  generatedDates: string[];
}

export type DashboardType = "payable" | "receivable";

// Maps a Fillout form to the client/dashboard it feeds. Created and deleted
// entirely through the admin "Connect Fillout Form" action — never hand-edited,
// never hardcoded — so onboarding a new client's form needs no code change.
export interface FilloutFormMapping {
  filloutFormId: string; // doc id
  clientId: string;
  dashboardType: DashboardType;
  label: string;
  webhookId: string; // Fillout's webhook id, needed to disconnect later
  createdAt: Timestamp;
}

export interface ClientProfile {
  clickupFolderId: string;
  clickupFolderName: string;
  monthlyWorkListId: string;
  syncedAt: Timestamp;
  // Admin-managed fields
  fullName?: string;
  executiveDirectorName?: string;
  coverImageUrl?: string;
  logoImageUrl?: string;
  servicesAvailed?: string[];
  clientLinks?: ClientLink[];
  formsEnabled?: boolean;
  forms?: ClientForm[];
  apCalendar?: ApCalendar;
  dashboardsEnabled?: Partial<Record<DashboardType, boolean>>;
  isActive?: boolean;
  createdAt?: Timestamp;
}

export interface UserRecord {
  uid: string;
  email: string;
  role: "admin" | "client" | "bookkeeper";
  clientId: string | null; // set for "client" role, null otherwise
  assignedClientIds?: string[]; // set for "bookkeeper" role, assigned by admin
  createdAt?: import("firebase/firestore").Timestamp;
}

export interface ChecklistItem {
  id: string;
  name: string;
  resolved: boolean;
  orderIndex: number;
}

export interface Task {
  taskId: string;
  name: string;
  description: string;
  status: string;
  dueDate: Timestamp | null;
  checklist: ChecklistItem[];
  // Custom fields
  client: string | null;
  cadence: string | null;
  responsibility: string | null;
  listType: string | null;
  taskType: string | null;
  workMonth: string | null;
  workYear: string | null;
  approvalRequired: boolean;
  syncedAt: Timestamp;
}

// ─── AP/AR transaction dashboards ───────────────────────────────────────────

// One entry per Fillout question id, auto-appended by the ingestion function
// the first time it sees a question id it hasn't recorded before. Never deleted
// when a question is removed from the live form — marked archived instead, so
// historical answers for that column stay visible.
export interface FormSchemaField {
  questionId: string;
  label: string;
  type: string; // Fillout's question type string, e.g. "ShortAnswer", "MultipleChoice", "FileUpload"
  order: number;
  archived?: boolean;
}

export interface FormSchema {
  clientId: string;
  dashboardType: DashboardType;
  filloutFormId: string;
  fields: FormSchemaField[];
}

// Field ownership — who is allowed to write which group. Enforced server-side
// in the write-field route, not just in the UI.
export type TransactionFieldOwner = "admin" | "bookkeeper" | "client";

// ─── Admin-defined manual/status fields ─────────────────────────────────────
// Fully dynamic, per client + dashboard — admin defines the field list (not a
// fixed set baked into the type system), including who's allowed to fill each
// one in. "category" is purely organizational (which section of the grid a
// field's column groups under); it doesn't affect write permission, which
// comes entirely from editableBy.

// "apDate" is a dropdown whose options come from the client's ApCalendar
// (effectiveApDates) rather than admin-typed options — admin opts into having
// an AP-run-date column at all by adding a field of this type; it's no longer
// a column every dashboard gets automatically.
export type ExtraFieldType = "text" | "number" | "date" | "dropdown" | "checkbox" | "apDate";
export type ExtraFieldCategory = "manual" | "status";
// Who besides admin (who can always edit everything) may fill this field in.
export type ExtraFieldEditor = "client" | "bookkeeper";

export interface ExtraFieldDef {
  id: string;
  label: string;
  category: ExtraFieldCategory;
  type: ExtraFieldType;
  options?: string[]; // "dropdown" only — "apDate"'s options come from the client's ApCalendar instead
  editableBy: ExtraFieldEditor;
  order: number;
}

export interface DashboardFieldConfig {
  clientId: string;
  dashboardType: DashboardType;
  fields: ExtraFieldDef[];
}

export interface TransactionRow {
  id: string; // == Fillout submissionId when source is "fillout", else a generated id
  clientId: string;
  dashboardType: DashboardType;
  source: "fillout" | "manual";
  submissionId?: string;
  submittedAt?: Timestamp;

  // Form-sourced answers, keyed by Fillout question id — open map so the schema
  // can evolve without a migration. Immutable through the app for every role
  // including admin — a fixed record of what was actually submitted.
  formAnswers: Record<string, unknown>;

  // Admin-defined manual/status fields, keyed by ExtraFieldDef.id. Schema and
  // write ownership come from that client+dashboard's DashboardFieldConfig,
  // not from anything fixed here — this map has no built-in structure. This is
  // also where an AP-run-date column lives now (a field with type "apDate"),
  // if admin has chosen to add one — it's opt-in, not automatic.
  extraFields: Record<string, unknown>;

  // Receipt/invoice links — array so one row can hold multiple links natively.
  // Structural, not admin-definable — every row gets this regardless of config.
  attachmentLinks: string[];

  lastModifiedBy?: string; // uid
  lastModifiedAt?: Timestamp;
}
